### ISSUE TITLE
Warning from ILI9488

### ISSUE THREAD

**Issue by spairo1741** [cfrankb/esp32-ili9488-jewel#1]
- some warning from compilation.
[warning.log](https://github.com/cfrankb/esp32-ili9488-jewel/files/13664510/warning.log)

[monitor.log](https://github.com/cfrankb/esp32-ili9488-jewel/files/13664511/monitor.log)

**Comment by cfrankb** [comment]
warnings fixed
https://github.com/cfrankb/esp32-ili9488-jewel/commit/56c4bf395bc83f25410ee39c2a0a353073142763

**Comment by spairo1741** [comment]
- now is working, a'la Tetris
