### ISSUE TITLE
move configuration to menuconfig

### ISSUE THREAD

**Issue by cfrankb** [cfrankb/esp32-ili9488-jewel#2]
the tft options and joysticks options to be moved to menuconfig to facilitate use by end users.

**Comment by spairo1741** [comment]
- but button A,B,C, D ? 
- this entry is blocking the game on esp32s3
- 7, 8, 9, 10 id for esp32s3, working good
![esp32s3-Nano](https://github.com/cfrankb/esp32-ili9488-jewel/assets/29607074/62402b68-b6d4-4529-adae-edb5e46e19a1)

**Comment by cfrankb** [comment]
![Screenshot_2023-12-14_07-29-54](https://github.com/cfrankb/esp32-ili9488-jewel/assets/3089730/7b101776-4f9c-478d-8f12-0fd8e0f1f6be)
https://github.com/cfrankb/esp32-ili9488-jewel/commit/e09d05d4b3a6deb475fbb5b71b19b00fb2b100fe

**Comment by cfrankb** [comment]
![Screenshot_2023-12-14_08-11-44](https://github.com/cfrankb/esp32-ili9488-jewel/assets/3089730/3a478503-125c-4eb6-a2e9-676a3c6b3257)

**Comment by cfrankb** [comment]
you have the buttons and joystick configured now
it will use either or both
to turn an option off. set it to -1


still not convinced this is the best option.
maybe i should just remove joystick altogether.

**Comment by cfrankb** [comment]
esp32 and esp32s3 have completely different GPIO layouts.
all the options were based on my esp32.
